### ISSUE TITLE
nedtrie no longer compiles clean, and glibs debug code reports error

### ISSUE THREAD

**Issue by sirzooro** [ned14/nedtries#9]
There are multiple problems with nedtrie.h, when compiled using g++ 4.4.6 on Linux. Example code is pasted below.
1. That code does not compile - compiler complains about undeclared memset(). I had to add `#include <string.h>` before `#include "nedtrie.h"`.
2. Compilation with -Wall -O2 reports few warnings of types -Winvalid-offsetof, -Wunused-variable, -Wstrict-aliasing.
3. Glibc debug code (enabled by -D_GLIBCXX_DEBUG) reports "error: attempt to copy-construct an iterator from a singular iterator."

Please fit these issues. Please also check it with latest g++ - new versions usually detects new warning types.

```
#include "nedtrie.h"

struct Test
{
    int key;
    Test(int key) : key(key) {}
};

struct TestKey : public std::unary_function<Test*, size_t>
{
    size_t operator()(const Test *RESTRICT v) const
    {
        return v->key;
    }
};

typedef nedtries::trie_map<size_t, Test*, TestKey> TestTrieMap;


int main()
{
    TestTrieMap trie_map;
    Test* pt = new Test(1);
    trie_map.insert(pt);
    
    return 0;
}
```

**Comment by ned14** [comment]
I think it much more likely that gcc 4.4 is the thing broken. Have a look at https://travis-ci.org/ned14/nedtries/jobs/55998807 where GCC 4.6 is used, there are no warnings with -Wall -O2. I also test GCC 4.9 here locally, also no warnings.

The GCC debug iterator warning is correct. No one sensible should use the tries based STL container, it is very hacky as the docs say.

The missing string.h include I don't see a problem with though.

**Comment by ned14** [comment]
Actually I've just realised the scons config sets:

"-Wno-unused-variable", "-Wno-unused-function", "-Wno-unused-but-set-variable", "-Wno-strict-aliasing"

This would explain why I don't see the warnings.

Pull requests are welcome, but I'd disable trie_map in the header first. No point in debugging that.

**Comment by ned14** [comment]
I've disabled the C++ STL containers which fixes this problem. Thanks for the report.
